### ISSUE TITLE
Error: Running the contributed command:'copyRelativePath' failed.

### ISSUE THREAD

**Issue by carmanchris31** [alexandrudima/vscode-copy-relative-path#1]
Running Version 1.7.1 (1.7.1) on OS X 10.11.6.

When trying to invoke the copy relative command through the command palette, I get this error.

However, if I invoke the command through the context menu on a file in the explorer pane, it works correctly.

Please let me know if there's anything further I can do or provide to help diagnose this issue.

**Comment by ValeriiVasin** [comment]
OS X 10.11.6
VSCode 1.7.2

Same issue. Any updates on this?

**Comment by OliverJAsh** [comment]
Same problem, but this works with this alternative extension https://github.com/enochcheung/copy-relative-path
