### ISSUE TITLE
I copy failed When i use copy-relative-path.

### ISSUE THREAD

**Issue by strongant** [alexandrudima/vscode-copy-relative-path#2]
- OS : Ubuntu14.04
- VScode Version:1.7.1

**Comment by carmanchris31** [comment]
@strongant Does this occur only through the command palette for you as well, and not through the file explorer context menu? (see https://github.com/alexandrudima/vscode-copy-relative-path/issues/1)

**Comment by alexdima** [comment]
dup of #1
