### ISSUE TITLE
[Windows] VSC 1.17.0 update : slashes now become backslashes

### ISSUE THREAD

**Issue by Paulmicha** [alexandrudima/vscode-copy-relative-path#3]
Expected : `path/to/file.ext`
Got : `path\to\file.ext`

**Comment by hua03** [comment]
@Paulmicha You can modify the extension source code.If you are a windows user, VSCode extensions generally on there `C:/Users/Administrator/.vscode/extensions` , and Linux  on there `~/.vscode/extensions`.
[Here](https://github.com/alexandrudima/vscode-copy-relative-path/pull/5/commits/055233d59199ec90b0ba5a656dec09b793c94f8e) you need to modify  .

**Comment by alexdima** [comment]
Resolved via PR #5
